// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugvtzaabdicxpzigenfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVndnR6YWFiZGljeHB6aWdlbmZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxODY4NTYsImV4cCI6MjA2Mzc2Mjg1Nn0.2SZEAYPlKoGeR_l8S-BlyPsXIhykHHOI7Ae6WJK2C6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);